server:
  port: 9000

spring:
  threads:
    virtual:
      enabled: true
  grpc:
    client:
      chat-service:
        address: 'static://localhost:9090'
        negotiation-type: plaintext
  application:
    name: chat-server
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: ${spring.application.name}
        instance-id: chat-server-${spring.application.instance-id:${random.value}}
        prefer-ip-address: true
        health-check-path: /actuator/health
        health-check-interval: 15s

management:
  endpoints:
    web:
      exposure:
        include: health,info
    endpoint:
      health:
        show-details: always

socket:
  host: localhost
  port: 9000
  context: "/socket.io"

jwt:
  secret: ${JWT_SECRET}

logging:
  level:
    com.example.chat: DEBUG
    com.datastax.oss.driver: INFO

